CREATE TABLE OWNER (
    OWNER_NAME VARCHAR(100) NOT NULL
);
CREATE TABLE PET (
    PET_ID INT NOT NULL,
    PET_NAME VARCHAR(100),
    OWNER_NAME VARCHAR(100),
    PRICE INT,
    BIRTH_DATE DATE
);