CREATE PROCEDURE CALC_PET_PRICE(IN IN_PET_ID INT, OUT OUT_PRICE INT)
	READS SQL DATA
BEGIN ATOMIC
	DECLARE genka INT;
	SET (genka) = (SELECT PRICE  FROM PET WHERE PET_ID=IN_PET_ID);
	SET (OUT_PRICE) = (genka * 1.08);
END
/